name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    env:
      CCACHE_MAXSIZE: 400M
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPRESS: 1

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: ./.github/workflows/deps/linux.sh

      - name: Retrieve cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-ccache-

      - name: Configure build
        run: |
          mkdir build
          cd build

          cmake \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_BUILD_TYPE=Debug \
            -G Ninja \
            ..

      - name: Build
        run: |
          cd build
          cmake --build .

          ccache -s


  macos:
    name: Build macOS (universal)
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: ./.github/workflows/deps/macos.sh

      - name: Configure build
        run: |
          mkdir build
          cd build

          # CMAKE_FIND_FRAMEWORK=LAST needs to be set to fix
          # a header/dylib version mismatch caused by Mono being present:
          # https://gitlab.kitware.com/cmake/cmake/-/issues/18921#note_601123
          
          # Build universal binary for both arm64 and x86_64
          # Same configuration as release workflow
          cmake \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_FIND_FRAMEWORK=LAST \
            -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
            -DBUILD_MACOS_BUNDLE=ON \
            -G Ninja \
            ..

      - name: Build
        run: |
          cd build
          cmake --build .
